import React, { useEffect } from 'react';
import { motion } from 'framer-motion';

const TermsConditions = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div style={{ paddingTop: '80px', minHeight: '100vh', background: 'var(--bg-white)' }}>
      <section className="section-padding">
        <div className="container" style={{ maxWidth: '900px' }}>
          
          {/* Header */}
          <div className="section-header" style={{ textAlign: 'left', margin: '0 0 50px 0' }}>
            <span className="subtitle">Terms of Service</span>
            <h1 style={{ fontSize: 'clamp(32px, 5vw, 56px)', color: 'var(--text-primary)', marginBottom: '16px' }}>
              Terms &amp; Conditions
            </h1>
            <p style={{ margin: 0, fontSize: '15px', color: 'var(--text-muted)' }}>
              Last updated: August 3, 2026
            </p>
          </div>

          {/* Terms Content */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            style={{
              lineHeight: '1.8',
              fontSize: '16px',
              color: 'var(--text-secondary)',
              fontWeight: 300,
              display: 'flex',
              flexDirection: 'column',
              gap: '32px'
            }}
          >
            <div>
              <p>
                Welcome to Urban Owls Digital. By accessing our website (<a href="https://urbanowls.co" style={{ color: 'var(--accent-gold)', fontWeight: 500 }}>urbanowls.co</a>) or utilizing our services, you agree to comply with and be bound by the following Terms and Conditions. Please review them carefully.
              </p>
            </div>

            <div>
              <h2 style={{ fontFamily: 'var(--font-heading)', fontSize: '24px', color: 'var(--text-primary)', marginBottom: '12px', fontWeight: 700 }}>
                1. Acceptance of Terms
              </h2>
              <p>
                By visiting our website, submitting project contact briefs, or entering into contracts with Urban Owls Digital, you acknowledge that you have read, understood, and agreed to these terms, which govern our relationship with you regarding our platform and services.
              </p>
            </div>

            <div>
              <h2 style={{ fontFamily: 'var(--font-heading)', fontSize: '24px', color: 'var(--text-primary)', marginBottom: '12px', fontWeight: 700 }}>
                2. Scope of Services
              </h2>
              <p>
                Urban Owls Digital provides premium digital products, including custom website designs, custom MERN stack software solutions, headless e-commerce builds, Google ranking &amp; SEO campaign configurations, and Generative Engine Optimization (GEO). Specific features, timelines, and deliverables are detailed in individual Service Level Agreements (SLA) or project scopes signed by the client.
              </p>
            </div>

            <div>
              <h2 style={{ fontFamily: 'var(--font-heading)', fontSize: '24px', color: 'var(--text-primary)', marginBottom: '12px', fontWeight: 700 }}>
                3. Intellectual Property Rights
              </h2>
              <p>
                Unless otherwise agreed in a separate contract:
              </p>
              <ul style={{ paddingLeft: '24px', display: 'flex', flexDirection: 'column', gap: '8px', marginTop: '12px' }}>
                <li>All preliminary mockups, animations, design styles, and coding snippets generated by Urban Owls Digital remain our intellectual property until the project is fully paid for.</li>
                <li>Upon final payment clearance, full ownership rights of the custom frontend codebase and custom assets will transition to the client, excluding any third-party frameworks (e.g., React, Node modules).</li>
              </ul>
            </div>

            <div>
              <h2 style={{ fontFamily: 'var(--font-heading)', fontSize: '24px', color: 'var(--text-primary)', marginBottom: '12px', fontWeight: 700 }}>
                4. Client Responsibilities
              </h2>
              <p>
                To deliver sub-second performance builds, clients are required to provide necessary content briefs, media assets, API credentials, and feedback loops inside the agreed timelines. Urban Owls Digital is not responsible for project delays caused by a lack of client materials or communication.
              </p>
            </div>

            <div>
              <h2 style={{ fontFamily: 'var(--font-heading)', fontSize: '24px', color: 'var(--text-primary)', marginBottom: '12px', fontWeight: 700 }}>
                5. Limitation of Liability
              </h2>
              <p>
                Urban Owls Digital designs high-ranking and secure environments. However, we are not liable for server downtime, third-party API changes, hosting provider failures, or search engine algorithm updates beyond our immediate codebase control.
              </p>
            </div>

            <div>
              <h2 style={{ fontFamily: 'var(--font-heading)', fontSize: '24px', color: 'var(--text-primary)', marginBottom: '12px', fontWeight: 700 }}>
                6. Amendments to Terms
              </h2>
              <p>
                We reserve the right to modify these terms at any time. Changes will be updated on this page with the matching "Last updated" date. Continued use of our website or services constitutes agreement to the updated terms.
              </p>
            </div>

            <div>
              <h2 style={{ fontFamily: 'var(--font-heading)', fontSize: '24px', color: 'var(--text-primary)', marginBottom: '12px', fontWeight: 700 }}>
                7. Contact Information
              </h2>
              <p>
                If you have any questions or clarifications regarding these Terms &amp; Conditions, please contact us at:
                <br />
                <strong>Email:</strong> <a href="mailto:hello@urbanowls.co" style={{ color: 'var(--accent-gold)' }}>hello@urbanowls.co</a>
              </p>
            </div>
          </motion.div>

        </div>
      </section>
    </div>
  );
};

export default TermsConditions;
